### ISSUE TITLE
1.0.2 version requires bungeeguard

### ISSUE THREAD

**Issue by faragilus** [ka0un/OPProtector#1]
Hey. I am using this plugin on an offline server to prevent students from joining as admins. It is super convenient that only the admins need to enter the passwords, while the rest of the students don't even notice the additional layer of security. But in version 1.0.2 it started demanding the bungeeguard installed and configured even though my server is a single server, not a network. 
The server is using paper 1.20.4
Using OPProtector 1.0.1 with server 1.20.4 constantly bans all non-op players like as if they are ops
Using OPProtector 1.0.2 with server 1.20.4 restarts the server when an OP logs in
Using OPProtector 1.0.2 with server 1.20.4 with Bungeeguard installed constantly restarts the server
The last working version was 1.0.1 on a 1.20.2 server, but simply downgrading it back is not an option because the worlds are now 1.20.4

Would be great to have an option to simply disable the shutdown on critical errors

**Comment by ka0un** [comment]
make sure online-mode is true on your properties.yml file

**Comment by kh0mka** [comment]
The author was inspired by the OPGuard plugin and decided to make OPProtector. I was looking for an alternative to OPGuard and found only this plugin, after which I was pleased. 

I was disappointed when the plugin started to require BungeeGuard if online-mode=false. This is strange, because why would you make such a plugin for online-mode=true, it is not necessary and the author, unfortunately, did not think about it.

In the end, I decided to put OPGuard, which has not been updated for a long time, but it stood up perfectly on version 1.20.4.

Why get inspired and then turn the plugin into a meaningless *.jar file.

**Comment by ka0un** [comment]
this issue will be quickly fixed with next update

**Comment by kh0mka** [comment]
What I saw today is that the plugin has been updated. Insanely grateful for version 1.0.3 and the removal of the BungeeGuard requirement. Many thanks to the author for his understanding.
